<?php
/*
Plugin Name: Keep it Fresh
Plugin URI: http://www.jonathankern.com/code/keepitfresh
Description: Keep it Fresh will stop WordPress from showing posts older than a set number of days or a specific date.
Version: 1.0
Author: Jonathan Kern
Author URI: http://www.jonathankern.com

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant and author attributions, this restriction, and the
following disclaimer, must be included in all copies of the Software, in
whole or in part, and all derivative works of the Software, unless such
copies or derivative works are solely in the form of machine-executable 
object code generated by a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

define("KIF_DOMAIN", "keepitfresh");
$kif_is_setup = false;
$kif_plugin = plugin_basename(__FILE__);
$kif_dir = "../wp-content/plugins".dirname("/".$kif_plugin);

define("KIF_MODE_OFF", "off");
define("KIF_MODE_DATE", "date");
define("KIF_MODE_DAYS", "days");

define("KIF_DATE_REGEX", "/[0-9]{4}-[0-9]{1,2}-[0-9]{1,2}/");

if(!$kif_is_included) {
	$kif_is_included = true;
	
	// Localization setup
	function kif_setup() {
		global $kif_is_setup;
		
		if($kif_is_setup)
			return;
		
		load_plugin_textdomain(KIF_DOMAIN, $kif_dir);
		$kif_is_setup = true;
	}
	
	function kif_install() {
		add_option("kif_mode", KIF_MODE_OFF);
		add_option("kif_cutoffdate", "");
		add_option("kif_cutoffdays", "");
	}
	register_activation_hook(__FILE__, "kif_install");
	
	function kif_settings_init() {
		register_setting("kif_settings", "kif_mode");
		register_setting("kif_settings", "kif_cutoffdate");
		register_setting("kif_settings", "kif_cutoffdays");
	}
	add_action("admin_init", "kif_settings_init");
	
	function kif_admin_pages_init() {
		add_options_page(__("Keep it Fresh", KIF_DOMAIN), __("Keep it Fresh", KIF_DOMAIN), "manage_options", "keepitfresh", "kif_admin_page");
	}
	add_action("admin_menu", "kif_admin_pages_init");
	
	function kif_admin_page() {
		kif_setup();
		
		$mode = get_option("kif_mode");
		$date = get_option("kif_cutoffdate");
		$days = get_option("kif_cutoffdays");
		
		$off_checked = $mode == KIF_MODE_OFF ? " checked=\"checked\"" : "";
		$date_checked = $mode == KIF_MODE_DATE ? " checked=\"checked\"" : "";
		$days_checked = $mode == KIF_MODE_DAYS ? " checked=\"checked\"" : "";
		
		?>
		
		<div class="wrap">
			<h2><?php _e("Keep it Fresh", KIF_DOMAIN); ?></h2>
			<form method="post" action="options.php">
				<?php settings_fields("kif_settings"); ?>
				<p class="form-table" style="margin-bottom:15px;">
					<input id="kif_mode_off" name="kif_mode" type="radio" value="<?php echo KIF_MODE_OFF ?>"<?php echo $off_checked; ?> />
					<label for="kif_mode_off"><?php _e("Off", KIF_DOMAIN); ?></label>
				</p>
				<p class="form-table" style="margin-bottom:15px;">
					<input id="kif_mode_date" name="kif_mode" type="radio" value="<?php echo KIF_MODE_DATE ?>"<?php echo $date_checked; ?> />
					<label for="kif_mode_date"><?php _e("Hide posts published before", KIF_DOMAIN); ?></label>
					<input id="kif_cutoffdate" type="text" maxchars="10" style="width:90px;" name="kif_cutoffdate" value="<?php echo htmlspecialchars($date); ?>" onfocus="document.getElementById('kif_mode_date').checked=true;" />
					<span class="description"><?php _e("(YYYY-MM-DD)", KIF_DOMAIN); ?></span>
				</p>
				<p class="form-table">
					<input id="kif_mode_days" name="kif_mode" type="radio" value="<?php echo KIF_MODE_DAYS ?>"<?php echo $days_checked; ?> />
					<label for="kif_mode_days"><?php _e("Hide posts older than", KIF_DOMAIN); ?></label>
					<input id="kif_cutoffdays" type="text" maxchars="10" class="small-text" name="kif_cutoffdays" value="<?php echo htmlspecialchars($days); ?>" onfocus="document.getElementById('kif_mode_days').checked=true;" />
					<?php _e("days", KIF_DOMAIN); ?>
				</p>
				<p class="submit">
					<input type="submit" class="button-primary" value="<?php _e("Save Changes"); ?>" />
				</p>
			</form>
		</div>
				
		<?php
	}
	
	function kif_where_filter($where = "") {
		global $wpdb;
		
		if(!is_admin()) {
			$mode = get_option("kif_mode");
			if($mode == KIF_MODE_DATE) {
				$date = get_option("kif_cutoffdate");
				
				// Only filter if the date is valid
				if(preg_match(KIF_DATE_REGEX, $date)) {
					$where .= " AND (post_type != 'post' OR post_date > '".$wpdb->escape($date)."')";
				}
			}
			elseif($mode == KIF_MODE_DAYS) {
				$days = get_option("kif_cutoffdays");
				
				if(is_numeric($days) && intval($days) > 0) {
					$where .= " AND (post_type != 'post' OR post_date > '".$wpdb->escape(date("Y-m-d", strtotime("-".$days." days")))."')";
				}
			}
		}
		
		// if the mode is KIF_MODE_OFF or we are in the admin area, we just leave the $where as is and return it
		
		return $where;
	}
	add_filter("posts_where", "kif_where_filter");
	add_filter("get_previous_post_where", "kif_where_filter");
	add_filter("get_next_post_where", "kif_where_filter");
}